name: Deploy conda env
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy environment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy environment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            export SCRIPT_DIR=${{secrets.GADI_REPO_PATH}}/scripts
            export CONDA_ENVIRONMENT=${{ inputs.environment }}
            eval $( grep ADMIN_DIR $SCRIPT_DIR/install_config.sh )
            eval $( grep BUILD_STAGE_DIR $SCRIPT_DIR/install_config.sh )
            "${SCRIPT_DIR}"/deploy.sh
